apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travelmap.fullname" . }}-backend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "travelmap.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "travelmap.fullname" . }}-backend
    spec:
      # --- 여기에 imagePullSecrets 필드를 추가 ---
      imagePullSecrets:
        - name: dockerhub-credentials
      # ---------------------------------------------
      containers:
        - name: backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.backend.env.SPRING_PROFILES_ACTIVE }}"

            # DB 환경 변수 설정
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/travelmap"
            - name: SPRING_DATASOURCE_USERNAME
              value: "travelmap"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secrets.dbPassword.secretName }}
                  key: {{ .Values.backend.secrets.dbPassword.secretKey }}

            # YouTube API Key 설정
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secrets.youtubeApiKey.secretName }}
                  key: {{ .Values.backend.secrets.youtubeApiKey.secretKey }}

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travelmap.fullname" . }}-frontend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "travelmap.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "travelmap.fullname" . }}-frontend
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}