apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travelmap.fullname" . }}-backend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "travelmap.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "travelmap.fullname" . }}-backend
    spec:
      containers:
          - name: backend
            image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
            imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.backend.service.port }}
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "{{ .Values.backend.env.SPRING_PROFILES_ACTIVE }}"
              - name: SPRING_DATASOURCE_URL
                value: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/travelmap"
              - name: SPRING_DATASOURCE_USERNAME
                value: "{{ .Values.db.username }}"
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.db.password.secretName }}
                    key: {{ .Values.db.password.secretKey }}
              - name: YOUTUBE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.backend.env.youtubeApiSecret }}
                    key: {{ .Values.backend.env.youtubeApiKey }}
            livenessProbe:
              httpGet:
                path: /
                port: {{ .Values.backend.service.port }}
            readinessProbe:
              httpGet:
                path: /
                port: {{ .Values.backend.service.port }}
            resources:
              {{- toYaml .Values.backend.resources | nindent 12 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travelmap.fullname" . }}-frontend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "travelmap.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "travelmap.fullname" . }}-frontend
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          resources:
            {{- with .Values.frontend.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}