{{ $fullName := include "travelmap.fullname" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-backend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "travelmap.name" . }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "travelmap.name" . }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-postgres
  labels:
    {{- include "travelmap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
      name: db
  selector:
    app: postgres