version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:16
    container_name: travelmap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: travelmap
      POSTGRES_USER: travelmap
      POSTGRES_PASSWORD: travelmap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - travelmap-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - travelmap-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - travelmap-network

networks:
  travelmap-network:

volumes:
  postgres_data:


## 네트워크 설정
#networks:
#  travelmap-network:
#    driver: bridge
#
## 볼륨 설정
#volumes:
#  postgres_data:
#    driver: local
#  backend_logs:
#    driver: local