## 데이터 저장용 볼륨
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
