replicaCount: 2

backend:
  image:
    repository: somlh1212/travelmap-backend
    tag: latest
    pullPolicy: Always
  service:
    port: 8080
  env:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travelmap
    SPRING_DATASOURCE_USERNAME: travelmap
    SPRING_DATASOURCE_PASSWORD:
      secretName: travelmap-secret
      secretKey: db-password
    YOUTUBE_API_KEY:
      secretName: travelmap-secret
      secretKey: youtube-api-key
  resources: {}

frontend:
  image:
    repository: somlh1212/travelmap-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources: {}