apiVersion: v1
kind: Service
metadata:
  name: travelmap-service
spec:
  type: NodePort
  selector:
    app: travelmap
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # 외부에서 접근할 수 있는 포트 (30000~32767 중 선택)
